name: first_mobile_app_test1
description: A new Flutter project.

publish_to: 'none' # Remove this line to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.2
  sqflite: ^2.4.2
  path: ^1.9.1
  video_player: ^2.2.12
  sqflite_common_ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/cat_wawa.jpg